"""add display_name to users

Revision ID: 980b805a9820
Revises: f9b7923e59e7
Create Date: 2026-09-30 20:26:45.964337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '980b805a9820'
down_revision: Union[str, None] = 'f9b7923e59e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
